### ISSUE TITLE
dnvm update-self error: Cannot bind argument to parameter Path

### ISSUE THREAD

**Issue by per-samuelsson** [aspnet/dnvm#391] opened 2015-08-10 07:01 UTC
Since some time back, `dnvm update-self` gives me this error.

```
%home%>dnvm update-self
Updating dnvm from https://raw.githubusercontent.com/aspnet/Home/dev/dnvm.ps1
Invoke-Command : Cannot bind argument to parameter 'Path' because it is null.
At C:\Users\Per\.dnx\bin\dnvm.ps1:1479 char:23
+         Invoke-Command <<<<  ([ScriptBlock]::Create("dnvm-$cmd $cmdargs"))
    + CategoryInfo          : InvalidData: (:) [Invoke-Command], ParameterBind 
   ingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,M 
   icrosoft.PowerShell.Commands.InvokeCommandCommand
```

I installed dnvm originally using the [standalone installation](http://docs.asp.net/en/latest/getting-started/installing-on-windows.html#install-the-net-version-manager-dnvm), and I'm on a **Win7 x64** environment. I'm running the above in the **standard command-prompt, not elevated** (but running it as an admin shows the same thing).

I've configured NuGet to be able to grab bits from the unstable feeds, and bringing down runtimes works fine. The only problem I have is the above.

Here's some dnvm info:

```
.NET Version Manager v1.0.0-beta6-10394
Current feed settings:
Default Stable: https://www.nuget.org/api/v2
Default Unstable: https://www.myget.org/F/aspnetvnext/api/v2
Current Stable Override: <none>
Current Unstable Override: <none>
```

Any help/pointers appreciated!

**Comment by BrennanConroy** [comment] 2015-08-10 15:58
@per-samuelsson It looks like you were unfortunate enough to grab the version ```dnvm update-self``` broke. Sorry about that! All you need to do is run the installation again using the link you provided and you should get a newer version with a working ```dnvm update-self```

**Comment by glennc** [comment] 2015-08-10 17:03
@per-samuelsson Closing this, if updating DNVM doesn't fix it then reopen it.

**Comment by per-samuelsson** [comment] 2015-08-10 18:39
@BrennanConroy Thanks for helping out!

> Sorry about that!

No worries at all. Theres no panic zone or anything.

> All you need to do is run the installation again using the link you provided and you should get a newer version with a working `dnvm update-self`

Unfortunatelly, the problem seem to persist. I was able to really get the new version by first manually deleting ´.dnx\bin` (if I didn't, the PS script thingy didn't replace it), and then ran the script: 
```
@powershell -NoProfile -ExecutionPolicy unrestricted -Command "&{$Branch='dev';iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.ps1'))}
```
from an elevated standard prompt.

With the newer version, I got the following (stripped) updated info:

```
.NET Version Manager v1.0.0-beta7-10408
By Microsoft Open Technologies, Inc.
usage: dnvm <command> [<arguments...>]

Current feed settings:
Default Stable: https://www.nuget.org/api/v2
Default Unstable: https://www.myget.org/F/aspnetvnext/api/v2
Current Stable Override: <none>
Current Unstable Override: <none>

    To use override feeds, set DNX_FEED and DNX_UNSTABLE_FEED environment keys respectively
```

When I issue `dnvm update-self`, I still get

```
Updating dnvm from https://raw.githubusercontent.com/aspnet/Home/dev/dnvm.ps1
Invoke-Command : Cannot bind argument to parameter 'Path' because it is null.
At C:\Users\Per\.dnx\bin\dnvm.ps1:1722 char:23
+         Invoke-Command <<<<  ([ScriptBlock]::Create("dnvm-$cmd $cmdargs"))
    + CategoryInfo          : InvalidData: (:) [Invoke-Command], ParameterBind 
   ingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,M 
   icrosoft.PowerShell.Commands.InvokeCommandCommand
```

> @per-samuelsson Closing this, if updating DNVM doesn't fix it then reopen it.

@glennc Seems I don't have the priviledges to do so.

**Comment by BrennanConroy** [comment] 2015-08-10 20:42
Where are you running ```dnvm update-self``` from? Command Prompt, Powershell, other?

**Comment by per-samuelsson** [comment] 2015-08-11 05:53
> Command Prompt, Powershell, other?

Command Prompt. Not elevated.

**Comment by per-samuelsson** [comment] 2015-08-11 05:55
> Command Prompt. Not elevated.

And just for the record: running it as an admin produce the same error.

**Comment by BrennanConroy** [comment] 2015-08-11 15:36
Could you do ```where dnvm``` and then ```dnvm``` and show the version. I can't repro this issue with the latest dnvm.

**Comment by per-samuelsson** [comment] 2015-08-11 15:40
> Could you do where dnvm and then dnvm and show the version. I can't repro this issue with the latest dnvm.

Location:
```
where dnvm
C:\Users\Per\.dnx\bin\dnvm.cmd
```

Version (trimmed the output a little):
```
dnvm

.NET Version Manager v1.0.0-beta7-10408
By Microsoft Open Technologies, Inc.
usage: dnvm <command> [<arguments...>]

Current feed settings:
Default Stable: https://www.nuget.org/api/v2
Default Unstable: https://www.myget.org/F/aspnetvnext/api/v2
Current Stable Override: <none>
Current Unstable Override: <none>

    To use override feeds, set DNX_FEED and DNX_UNSTABLE_FEED environment keys respectively
```

**Comment by BrennanConroy** [comment] 2015-08-11 15:52
Could you open the dnvm.ps1 and show the contents of function dnvm-update-self

**Comment by per-samuelsson** [comment] 2015-08-11 18:10
```powershell
<#
.SYNOPSIS
    Updates DNVM to the latest version.
.PARAMETER Proxy
    Use the given address as a proxy when accessing remote server
#>
function dnvm-update-self {
    param(
        [Parameter(Mandatory=$false)] 
        [string]$Proxy)

    _WriteOut "Updating $CommandName from $DNVMUpgradeUrl"
    $wc = New-Object System.Net.WebClient
    Apply-Proxy $wc -Proxy:$Proxy
    
    $dnvmFile = Join-Path $PSScriptRoot "dnvm.ps1"
    $tempDnvmFile = Join-Path $PSScriptRoot "temp"
    $backupFilePath = Join-Path $PSSCriptRoot "dnvm.ps1.bak"

    $wc.DownloadFile($DNVMUpgradeUrl, $tempDnvmFile)

    if(Test-Path $backupFilePath) {
        Remove-Item $backupFilePath -Force
    }

    Rename-Item $dnvmFile $backupFilePath
    Rename-Item $tempDnvmFile $dnvmFile
}
```

**Comment by BrennanConroy** [comment] 2015-08-17 20:26
The third Join-Path call has a capitol c in $PSScriptRoot, that's the only strange thing I can see.

I am unable to reproduce your error.

**Comment by kcootedinh** [comment] 2015-08-18 00:06
I'm also experiencing this error with basically the same symptoms. I was recently forced to use a different machine and installed Visual Studio 2015 just yesterday. I started with beta5 and tried to update to beta6. 

I'm running from Command Shell, Win7-64, and I have managed to update using instructions above.

It's not causing any major issues, just thought I would add the problem isn't for just one person.

Updating dnvm from https://raw.githubusercontent.com/aspnet/Home/dev/dnvm.ps1
Invoke-Command : Cannot bind argument to parameter 'Path' because it is null.
At C:\Users\kcoote\.dnx\bin\dnvm.ps1:1722 char:23
+         Invoke-Command <<<<  ([ScriptBlock]::Create("dnvm-$cmd $cmdargs"))
    + CategoryInfo          : InvalidData: (:) [Invoke-Command], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.InvokeCommandCommand

**Comment by BrennanConroy** [comment] 2015-08-18 04:34
Ah Win7! I forgot thats what the original post said. I'll give this a try.

**Comment by per-samuelsson** [comment] 2015-08-18 06:56
> Ah Win7! I forgot thats what the original post said. I'll give this a try.

@BrennanConroy 

The weird thing is that for me, from like some day(s) back, this suddendly doesn't happen any more. Now, `dnvm update-self` runs like a charm.

AFAIK, my setup is the same in this context. I've brought down a couple of runtimes back, did some testing of them, deleted them, that kind of stuff. But nothing that really relate to `dnvm` as far as I know.

Ah, when writing this, I just remembered one thing I did - I updated Powershell from 2.0 -> 4.0, because I wanted to be able to build DNX. Thats most likely what fixed it. Maybe that can help in your researching.

FWIW, here's now my current dnvm (after just running `update-self`):

````
.NET Version Manager v1.0.0-beta7-10410
Current feed settings:
Default Stable: https://www.nuget.org/api/v2
Default Unstable: https://www.myget.org/F/aspnetvnext/api/v2
Current Stable Override: <none>
Current Unstable Override: <none>
```

**Comment by dg9ngf** [comment] 2015-08-23 13:59
I had the same error on Windows 7 x64 with VS 2015 and no further updates installed. Upgrading from PowerShell 2.0 or 3.0 (not sure anymore) to 4.0 resolved the error. It seems that this feature simply requires a newer PowerShell version to run. I've seen this in some of my own PowerShell scripts as well. I've added a version check in my scripts after I found out what minimum version is required.

**Comment by kcootedinh** [comment] 2015-08-24 01:18
I also upgraded to Powershell 4.0 and the issue no longer occurs for me.

**Comment by glennc** [comment] 2015-09-04 17:47
There is a minimum in the scripts already, but apparently it is too low. We also kind of want to work on PowerShell 2.0 if we can. For exactly the scenario you guys are in.

We run our tests telling PowerShell to run in 2.0 mode, but apparently this is something that is missed by that. I would like to fix this if I can. Any of you still have a PowerShell 2.0 machine that your willing to isolate the fix? If not I will add it to the backlog and we will get try to get to it in the next Milestone.

**Comment by per-samuelsson** [comment] 2015-09-04 18:29
> I would like to fix this if I can. Any of you still have a PowerShell 2.0 machine that your willing to isolate the fix? If not I will add it to the backlog and we will get try to get to it in the next Milestone.

For me, I'm pass this, after upgrading to PS 4.0, as I wrote earlier. 

But if you can provide me with some instructions to downgrade (if at all possible), I can volonteer to help out testing/reporting based on your instructions. I really enjoy this whole new stack of yours, and I feel its the least I can do to give something back :hand: 

Let me know if you want me to do that.

**Comment by dg9ngf** [comment] 2015-09-04 18:34
I just checked and my second machine is still on PS 2.0. It has VS 2015 RTM installed, no upgrades of anything yet. I can reproduce the original issue there. What should I do?

**Comment by evancox10** [comment] 2015-09-08 21:33
I'm still on PS2.0 and can reproduce the error too. VS 2015 RTM on Windows 7 Pro.

**Comment by hubuk** [comment] 2015-09-17 08:23
The error is caused by lack of $PSScriptRoot varaible in PowerShell 2.0. Im not experienced in PowerShell but adding following check to dnvm-update-self function should be sufficient in this case:
```PowerShell
if (!$PSScriptRoot -Or $PSScriptRoot -eq "")
{
    $PSScriptRoot = Split-Path $script:MyInvocation.MyCommand.Path -Parent
}
```
Can someone confirm correctness of this approach?

**Closed** 2017-12-17 19:50 UTC
