### ISSUE TITLE
No command 'dnx' found

### ISSUE THREAD

**Issue by jaliyaudagedara** [aspnet/dnvm#231] opened 2015-04-24 05:42 UTC
I did setup dnvm on my ubuntu.
![2015-04-24_13-32-26](https://cloud.githubusercontent.com/assets/5653381/7314894/8bbc150a-ea86-11e4-9a8e-f851653d4b93.png)

When I dnvm list,
![2015-04-24_13-32-26](https://cloud.githubusercontent.com/assets/5653381/7314911/b192551e-ea86-11e4-8fcc-ea14d8cc702b.png)

When I run **dnvm use default**,
**Cannot find dnx-mono.1.0.0-beta5-11596, do you need to run 'dnvm install default'?**

And when I try to run dnvm upgrade, it's giving me the following.
**"Error: Could not find latest version from feed https://nuget.org/api/v2"**

My nuget config as follows.
>&lt;?xml version="1.0" encoding="utf-8"?&gt;
&lt;configuration&gt;
  &lt;packageSources&gt;
    &lt;add key="AspNetVNext" value="https://www.myget.org/F/aspnetvnext/api/v2/" /&gt;
    &lt;add key="nuget.org" value="https://www.nuget.org/api/v2/" /&gt;
  &lt;/packageSources&gt;
  &lt;disabledPackageSources /&gt;
&lt;/configuration&gt;

dnvm upgrade -u does work with following.
>[mono-20150421154735]jaliya@JALONUBUNTU:~/.dnx/runtimes/dnx-mono.1.0.0-beta5-11596$ dnvm upgrade -u
Determining latest version
Latest version is 1.0.0-beta5-11596
dnx-mono.1.0.0-beta5-11596 already installed.
Cannot find dnx-mono.1.0.0-beta5-11596, do you need to run 'dnvm install 1.0.0-beta5-11596'?

And when I run dnx, it says **No command 'dnx' found**

When I navigated to **~/.dnx/runtimes/dnx-mono.1.0.0-beta5-11596**, nupkg is not extracted.

So when I try to install using,
>[mono-20150421154735]jaliya@JALONUBUNTU:~/.dnx/runtimes/dnx-mono.1.0.0-beta5-11596$ dnvm install dnx-mono.1.0.0-beta5-11596.nupkg

it's giving me the following.

>dnx-mono.1.0.0-beta5-11596 already installed
Cannot find dnx-mono.1.0.0-beta5-11596, do you need to run 'dnvm install 1.0.0-beta5-11596'?

This is weird. What can be the issue here?

**Comment by zhengchun** [comment] 2015-04-24 09:48
are you installed a `mono`? vnext need install a 4.1 version of mono.
i'm following the [aspnet/home](https://github.com/aspnet/Home/) docs ,it can working on my `centos 6.5` ystem.

**Comment by jaliyaudagedara** [comment] 2015-04-24 11:31
yeah, running on Mono JIT compiler version 4.1.0.

**Comment by muratg** [comment] 2015-04-24 16:25
@jaliyaudagedara Can you try ```dnvm upgrade -Unstable```?  Not being able to find the installed dnx is still weird though. /cc: @glennc

**Comment by jaliyaudagedara** [comment] 2015-04-24 18:22
Ran dnvm upgrade -unstable, still the same.
![2015-04-24_23-50-13](https://cloud.githubusercontent.com/assets/5653381/7325569/bd42fb60-eadc-11e4-806b-ebc49654a8a0.png)

**Everything is up and running using kvm, but not with dnvm.**

**Comment by cnblogs-dudu** [comment] 2015-06-17 03:48
See [Cannot find dnx-mono.1.0.0-beta4](https://github.com/aspnet/Home/issues/616#issuecomment-104090164)
> install unzip - sudo apt-get install unzip - then run dnvm upgrade

**Comment by halter73** [comment] 2015-06-23 02:32
Nice catch @cnblogs-dudu. It looks like #616 is a dupe of this issue.

I've updated the [Getting Started Guide](https://github.com/aspnet/Home/blob/dev/GettingStartedDeb.md) to show that "unzip" needs to be installed.

@jaliyaudagedara If this doesn't fix your issue, feel free to reopen.

**Closed by halter73** 2015-06-23 02:32 UTC

**Comment by jaliyaudagedara** [comment] 2015-06-23 02:59
@cnblogs-dudu and @halter73, Thank you much for the help. This issue was opened like 2 months back, I have managed to fix the issue. Thanks again.
