### ISSUE TITLE
Unable to load Linux Mint (17.1) Desktop Environment after installing DNVM

### ISSUE THREAD

**Issue by ankeshdave** [aspnet/dnvm#222] opened 2015-04-17 10:12 UTC
I can confirm that i am facing this issue every time i install dnvm/kvm on Linux Mint 17.1.
The "Cinnamon" desktop profile session is corrupted.

### Steps to reproduce
* Install Dnvm/kvm (Following the home page instructions)
* Run Kestrel and HelloMVC Sample (Test if installed correctly).
* Logout Linux Mint (17.1 Ubuntu 14.04)
* Login
* Error [Unable to boot]  

### Workaround i am currently using 
* Edit **$HOME/.profile** using alternative shell (ctrl +alt + F3)
*  comment  
    `[ -s "/home/android/.dnx/dnvm/dnvm.sh" ] && . "/home/android/.dnx/dnvm/dnvm.sh" # Load dnvm`
* Get back to desktop shell
* Login

#### Stackoverflow issue (When i was using kvm)
http://stackoverflow.com/q/27701764/756987

#### Screenshots
![kdtj4](https://cloud.githubusercontent.com/assets/1351658/7199814/455c51e0-e515-11e4-8069-9df1a2e1cbd2.png)
![nj1yn](https://cloud.githubusercontent.com/assets/1351658/7199819/4ba1ac6c-e515-11e4-8a70-7ddf516b6f14.png)

**Comment by glennc** [comment] 2015-04-20 17:02
This happens if the dnvm.sh has an error. Where did you install dnvm from?

**Comment by ankeshdave** [comment] 2015-04-21 08:30
I installed dnvm from the instructions given in `aspnet/Home` github page. 
I used the following command to install dnvm
```perl  
curl -sSL https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.sh | DNX_BRANCH=dev sh && source ~/.dnx/dnvm/dnvm.sh
```  
:notebook:  I installed it on a fresh machine as well as a vm (Fresh Linux mint installed)
:information_source:  I have created a fresh vm again, If  you have some specific instructions you want me to try again :smile:

**Comment by WilfriedB** [comment] 2015-04-28 18:55
I had this problem as well. The cause is that the dnvm.sh must be run with bash but the logon process uses dash, not bash. dnvm.sh is not a valid dash script and throws an error.

**Comment by erdemkemer** [comment] 2015-05-01 19:12
@WilfriedB  so how did you solved issue ? comment out from .profile ?

**Comment by ankeshdave** [comment] 2015-05-02 06:41
@erdemkemer   I believe he would have changed his default shell to bash.
@WilfriedB  ??

**Comment by WilfriedB** [comment] 2015-05-02 11:02
@erdemkemer @ankeshdave I commented it out from .profile and start the the script by typing "source .dnx/dnvm/dnvm.sh" when I need it.

**Comment by markyjones** [comment] 2015-05-06 09:31
I went around the houses on this one too. It looks like the one solution would be to alter the dnvm.sh script to use "POSIX standard, omitting those items flagged as XSI extensions" https://wiki.ubuntu.com/DashAsBinSh.

In the short term I have modified my .profile file to call via bash directly

before

`[ -s "/home/mark/.dnx/dnvm/dnvm.sh" ] && . "/home/mark/.dnx/dnvm/dnvm.sh" # Load dnvm`

after

`[ -s "bash /home/mark/.dnx/dnvm/dnvm.sh" ] && . "bash /home/mark/.dnx/dnvm/dnvm.sh" # Load dnvm`

**Comment by Nikon-The-Third** [comment] 2015-05-06 17:32
Since ``~/.profile`` already checks if ``~/.bashrc`` exists and sources it (but only when ``bash`` is the current shell), I think the correct way to solve this is by:

Removing the line that sources dnvm from ``~/.profile``.

Adding the line to ``~/.bashrc`` (or even modify it so it uses ``$HOME`` instead of the path).

**My ~/.profile:**

```
# ~/.profile: executed by the command interpreter for login shells.
# This file is not read by bash(1), if ~/.bash_profile or ~/.bash_login
# exists.
# see /usr/share/doc/bash/examples/startup-files for examples.
# the files are located in the bash-doc package.

# the default umask is set in /etc/profile; for setting the umask
# for ssh logins, install and configure the libpam-umask package.
#umask 022

# if running bash
if [ -n "$BASH_VERSION" ]; then
    # include .bashrc if it exists
    if [ -f "$HOME/.bashrc" ]; then
	. "$HOME/.bashrc"
    fi
fi

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/bin" ] ; then
    PATH="$HOME/bin:$PATH"
fi
```

**My ~/.bashrc:**

```
[ -s "$HOME/.dnx/dnvm/dnvm.sh" ] && . "$HOME/.dnx/dnvm/dnvm.sh" # Load dnvm
```

**Comment by Nikon-The-Third** [comment] 2015-05-06 17:43
@markyjones Your fix doesn't actually work.

Firstly, the ``[ -s XXX ]`` command [checks if the file ``XXX`` exists and is not empty](http://unixhelp.ed.ac.uk/CGI/man-cgi?test), so by prepending ``bash``, this no longer points to the file, and the second part of the line is never executed.

Secondly, ``.`` (or its bash alias ``source``), [runs the given file in the current shell](http://superuser.com/a/46146), so, again, by prepending ``bash``, this will not work.

**Comment by markyjones** [comment] 2015-05-06 17:48
Sorry my ignorance there - at least it got my login session starting correctly rather than crashing (if only by accident).

**Comment by ankeshdave** [comment] 2015-05-16 05:55
@glennc 
If i create an empty `.bashrc` file in `$HOME` and then install `dnvm` the line
```
[ -s "$HOME/.dnx/dnvm/dnvm.sh" ] && . "$HOME/.dnx/dnvm/dnvm.sh" # Load dnvm
```
is added to `.bashrc` file and not to `.profile`
I think you can write this as a part of installation instruction for [Debian Derivatives](https://github.com/aspnet/Home/blob/dev/GettingStartedDeb.md)

**Comment by cwhite92** [comment] 2015-06-20 23:00
Had exactly the same problem under Linux mint 17.1, @Nikon-The-Third's fix worked like a charm!

**Comment by lgtelles** [comment] 2015-07-24 18:44
@Nikon-The-Third fix worked like a charm on my case too. I think it should be corrected in future releases!

**Comment by glennc** [comment] 2015-09-02 17:43
I think we are going to stop sourcing dnvm in the .profile. Unfortunately this means many people will no longer automatically get it when they run the DNVMInstall.sh, they will have to add the line themselves. But it does avoid this problem from happening in the future.

https://github.com/aspnet/Home/pull/771

Closing this, as the actual issue reported was resolved some time ago.

**Closed by glennc** 2015-09-02 17:43 UTC
