### ISSUE TITLE
Cannot install DNVM

### ISSUE THREAD

**Issue by wangkanai** [aspnet/dnvm#217] opened 2015-04-13 17:13 UTC
I trying to install `DNVM` and i get the following error
```
C:\Users\Sarin Na Wangkanai>dnvm upgrade
WARNING: Found a KRE_HOME environment variable. This variable has been deprecated and should be removed, or it may interfere with DNVM and the .NET Execution en
vironment
Determining latest version
Downloading dnx-clr-win-x86.1.0.0-beta5-11533 from https://www.myget.org/F/aspnetvnext/api/v2
Installing to C:\Users\Sarin Na Wangkanai\.dnx\runtimes\dnx-clr-win-x86.1.0.0-beta5-11533
Adding C:\Users\Sarin Na Wangkanai\.dnx\runtimes\dnx-clr-win-x86.1.0.0-beta5-11533\bin to process PATH
Adding C:\Users\Sarin Na Wangkanai\.dnx\runtimes\dnx-clr-win-x86.1.0.0-beta5-11533\bin to user PATH
Updating alias 'default' to 'dnx-clr-win-x86.1.0.0-beta5-11533'
'""C:\Users\Sarin' is not recognized as an internal or external command,
operable program or batch file.
The system cannot find the path specified.
C:\Users\Sarin Na Wangkanai>
```
everything looks fine when i just run `DNVM`
```
C:\Users\Sarin Na Wangkanai>dnvm
WARNING: Found a KRE_HOME environment variable. This variable has been deprecated and should be removed, or it may interfere with DNVM and the .NET Execution en
vironment
You must specify a command!
   ___  _  ___   ____  ___
  / _ \/ |/ / | / /  |/  /
 / // /    /| |/ / /|_/ /
/____/_/|_/ |___/_/  /_/
.NET Version Manager v1.0.0-beta5-10365
By Microsoft Open Technologies, Inc.

usage: dnvm <command> [<arguments...>]

commands:
    alias           Lists and manages aliases
    exec            Executes the specified command in a sub-shell where the PATH has been augmented to include the specified DNX
    help            Displays a list of commands, and help for specific commands
    install         Installs a version of the runtime
    list            Lists available runtimes
    run             Locates the dnx.exe for the specified version or alias and executes it, providing the remaining arguments to dnx.exe
    setup           Installs the version manager into your User profile directory
    update-self     Updates DNVM to the latest version.
    upgrade         Installs the latest version of the runtime and reassigns the specified alias to point at it
    use             Adds a runtime to the PATH environment variable for your current shell
'""C:\Users\Sarin' is not recognized as an internal or external command,
operable program or batch file.
The system cannot find the path specified.
```
Thanks

**Comment by graemechristie** [comment] 2015-04-14 15:10
My guess is this has something  to do with it.

**Comment by glennc** [comment] 2015-04-16 18:03
This looks like the issue we have with spaces in usernames. A couple of people have hit it, we need to track it down and fix it.

**Comment by muratg** [comment] 2015-04-20 20:45
Dupe of https://github.com/aspnet/dnvm/issues/190

**Closed by muratg** 2015-04-20 20:45 UTC

**Comment by vermegi** [comment] 2015-04-28 08:00
I got the same error, but no spaces in my path. I did still have the kvm runtime installed. Removing the KRE_HOME environment variable fixed it for me.

**Comment by xtianus79** [comment] 2015-05-26 00:59
how do you remove KRE?

**Comment by radenkozec** [comment] 2015-07-22 12:08
@xtianus79  Remove it from Windows Environment Variables

**Comment by irejwanul** [comment] 2015-10-15 21:16
Following link is the guide for removing KRE_HOME variables ,,, http://www.digitalcitizen.life/simple-questions-what-are-environment-variables
