### ISSUE TITLE
`dnvm install` leaves .dnx folder behind after a failure, preventing recovery

### ISSUE THREAD

**Issue by dougbu** [aspnet/dnvm#189] opened 2015-03-25 02:34 UTC
e.g. 1.0.0-beta4-11360 is currently my default version.  executing `dnvm install default -arch x86 –runtime coreclr` reliably results in the spew at the bottom of this description.

worse than the spew, the command leaves $env:userprofile.dnx\runtimes\dnx-coreclr-win-x86.1.0.0-beta4-11360 behind.  so later executions of the command consistently result in `'dnx-coreclr-win-x86.1.0.0-beta4-11360' is already installed.`  stuck until I delete that directory.

minor but note also the useless `do you need to run 'dnvm install 1.0.0-beta4-11360'?` question in the middle of the spew.

```
Downloading dnx-coreclr-win-x86.1.0.0-beta4-11360 from https://www.myget.org/F/aspnetvolatile/api/v2
Exception calling "DownloadFile" with "2" argument(s): "The remote server returned an error: (404) Not Found."
At C:\Program Files\Microsoft ASP.NET 5\Dnvm\dnvm.ps1:452 char:5
+     $wc.DownloadFile($url, $DestinationFile)
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException

Exception calling "ExtractToDirectory" with "2" argument(s): "Could not find file
'C:\Users\dougbu\.dnx\runtimes\temp\dnx-coreclr-win-x86.1.0.0-beta4-11360.nupkg'."
At C:\Program Files\Microsoft ASP.NET 5\Dnvm\dnvm.ps1:476 char:9
+         [System.IO.Compression.ZipFile]::ExtractToDirectory($DownloadFile, $Unpa ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : FileNotFoundException

Remove-Item : Cannot find path 'C:\Users\dougbu\.dnx\runtimes\temp\dnx-coreclr-win-x86.1.0.0-beta4-11360.nupkg'
because it does not exist.
At C:\Program Files\Microsoft ASP.NET 5\Dnvm\dnvm.ps1:479 char:9
+         Remove-Item $DownloadFile -Force
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\dougbu...ta4-11360.nupkg:String) [Remove-Item], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.RemoveItemCommand

Installing to C:\Users\dougbu\.dnx\runtimes\dnx-coreclr-win-x86.1.0.0-beta4-11360
Cannot find dnx-coreclr-win-x86.1.0.0-beta4-11360, do you need to run 'dnvm install 1.0.0-beta4-11360'?
At C:\Program Files\Microsoft ASP.NET 5\Dnvm\dnvm.ps1:1069 char:9
+         throw "Cannot find $runtimeFullName, do you need to run '$CommandName in ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Cannot find dnx...0-beta4-11360'?:String) [], RuntimeException
    + FullyQualifiedErrorId : Cannot find dnx-coreclr-win-x86.1.0.0-beta4-11360, do you need to run 'dnvm install 1.0.
   0-beta4-11360'?
```

**Comment by davidfowl** [comment] 2015-03-25 06:04
+1 This is pretty annoying

**Comment by anurse** [comment] 2015-03-25 17:05
This should be fixed already in the latest DNVMs. It looks like you're using the MSI-installed DNVM, perhaps you need to update it or adjust your PATH?

/cc @glennc

**Comment by dougbu** [comment] 2015-03-25 18:57
`dnvm --version` shows `v1.0.0-beta4-10338`

further `dnvm.ps1` in my `$env:path` exactly matches latest KoreBuild package.  so I have the latest that's easily-found.

but Universe seems pretty far behind the DNVM repo.  that may be where the problem is.

**Comment by anurse** [comment] 2015-03-25 19:20
That sounds like the problem. Can we move this to a Universe bug to update KoreBuild?

**Comment by dougbu** [comment] 2015-03-25 19:23
why not just update Universe and reference this bug in the commit description?

**Comment by dougbu** [comment] 2015-03-28 00:06
this problem is fixed in the version at \\projectk-tc\Drops\dotnetsdk\dev\10340\dnvm.ps1.  but more-recent versions of that file (e.g. those currently in the DNVM and dotnetsdk repos) fail as described in this issue.

**Comment by BrennanConroy** [comment] 2015-05-20 17:42
This looks fixed on Windows, but on Linux:
```
azureuser@DNXTESTLinux:~$ dnvm install 1.0.0-beta5-11723
Downloading dnx-mono.1.0.0-beta5-11723 from https://www.nuget.org/api/v2
Download: https://www.nuget.org/api/v2/package/dnx-mono/1.0.0-beta5-11723
######################################################################## 100.0%
dnx-mono.1.0.0-beta5-11723 was not found in repository https://www.nuget.org/api/v2
This is most likely caused by the feed not having the version that you typed. Check that you typed the right version and try again. Other possible causes are the feed doesn't have a DNX of the right name format or some other error caused a 404 on the server.
```

Which leaves the bad dnx-mono.1.0.0-beta5-11723 folder.

**Comment by natemcmaster** [comment] 2015-07-24 18:46
:+1: Still broken on Linux/OS X.

**Comment by mholo65** [comment] 2015-08-02 19:26
Duplicate of #327, was probably fixed with 1aaa9fa.

**Comment by glennc** [comment] 2015-08-11 04:23
@BrennanConroy Can you do some testing that this is no longer happening during all the work you are about to start on dnvm.sh?

**Comment by natemcmaster** [comment] 2015-08-13 16:36
Can still happen on DNVM 1.0.0-beta7-10410.

Repro:
`dnvm install /Volumes/Drops/DNX-Darwin/dev/12356/dnx-coreclr-darwin-x64.1.0.0-beta7-12348.nupkg`
This *.nupkg file does not exists, but DNVM creates a folder anyways.

**Closed** 2017-12-17 19:51 UTC
Labels: 1 - Ready, bug
