### ISSUE TITLE
Consider uninstall/delete option

### ISSUE THREAD

**Issue by moozzyk** [aspnet/dnvm#302] opened 2015-06-18 00:27 UTC
Currently there is no way to uninstall a runtime. You can go and delete the folder but it feels a bit hacky and as a user I would wonder if deleting a folder is just enough or maybe something else needs to be done (especially that everything else is being done with the dnvm command)

**Comment by davidfowl** [comment] 2015-06-18 00:28
Dupe of https://github.com/aspnet/dnvm/issues/254

**Closed by davidfowl** 2015-06-18 00:28 UTC
